Sprint 11
vadamask/ImageFeed pull request #4
Opened 2023-07-12 18:28 UTC by vadamask

2023-07-13 14:32 UTC, protos17 requested changes

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/Constants.swift
> +let DefaultBaseURL = URL(string: "https://api.unsplash.com")
Рекомендую поместить их в енам и обращаться через static let

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    func config(with indexPath: IndexPath) {
Рекомендую создать модель для ячейки, а для конфигурации использовать модель:

func configure(with: model: ImagesListCellModel) {
cellImage.image = model.image
...
}
struct ImagesListCellModel {
let image: UIImage?
...
}

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2Service.swift
> +fileprivate let accessTokenURL = "https://unsplash.com/oauth/token"
Рекомендую перенести в Constants

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2Service.swift
> +    var isLoading = false
Публичные свойства принято писать перед приватными

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2Service.swift
> +                self.task = nil
self.task = nil дублируется, рекомендую оставить одну в общей области видимости

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2TokenStorage.swift
> +            KeychainWrapper.standard.string(forKey: "token")
"token" рекомендую указать как приватную константу

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2TokenStorage.swift
> +            assert(newValue != "", "token is wrong")
Здесь рекомендую заменить на проверку через guard let

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/ProfileService/ProfileImageService.swift
> +    static let DidChangeNotification = Notification.Name(rawValue: "ProfileImageProviderDidChange")
Константы и переменные принято писать с маленькой буквы, рекомендую поправить

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/ProfileService/ProfileService.swift
> +        let bio: String
Эти поля необходимо сделать опциональными, они могут не придти с сервера

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/ProfileService/ProfileService.swift
> +    }
Полностью дублирует ProfileResult, рекомендую для избавления от дублирования кода использовать везде ProfileResult, а ProfileViewModel удалить

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/ProfileService/ProfileService.swift
> +                completion(.success(profile))
completion рекомендую указывать последним

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/ProfileService/ProfileService.swift
> +                self.task = nil
self.task = nil дублируется, рекомендую перенести в общую область видимости

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                assertionFailure(error.localizedDescription)
Здесь рекомендую тоже отобразить ошибку:

showAlert()

2023-07-13 14:32 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: profile.username) { _ in }
switchToTabBarController() рекомендую указать в этом замыкании

2023-07-13 15:50 UTC, vadamask commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    func config(with indexPath: IndexPath) {
А модель в класс поместить или в отдельный файл?

2023-07-13 15:54 UTC, protos17 commented on ImageFeed/ImagesList/ImagesListCell.swift
> +    func config(with indexPath: IndexPath) {
Можно сделать и так и так, но лучше в класс поместить

2023-07-13 16:11 UTC, vadamask commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2TokenStorage.swift
> +            KeychainWrapper.standard.string(forKey: "token")
В этой же структуре?

2023-07-13 16:14 UTC, vadamask commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2TokenStorage.swift
> +            KeychainWrapper.standard.string(forKey: "token")
Тогда я теряю возможность использовать статик

2023-07-13 16:28 UTC, vadamask commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2TokenStorage.swift
> +            KeychainWrapper.standard.string(forKey: "token")
Указал константу тоже как статик и всё решилось

2023-07-13 16:33 UTC, vadamask commented on ImageFeed/ServiceAccessLayer/ProfileService/ProfileImageService.swift
> +    static let DidChangeNotification = Notification.Name(rawValue: "ProfileImageProviderDidChange")
Задавал этот вопрос наставникам. Говорят раньше мода такая была :)

2023-07-13 17:28 UTC, vadamask commented on ImageFeed/ServiceAccessLayer/ProfileService/ProfileService.swift
> +    }
Не совсем одинаковые, но одно можно сделать из другого. Окей

2023-07-14 10:05 UTC, protos17 approved these changes

2023-07-14 10:05 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2Service.swift
> +            self.task = nil
Рекомендую указать его до switch, чтобы completion вызывался последним

2023-07-14 10:05 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2TokenStorage.swift
> +    static private let tokenKey = "token"
Рекомендую заменить последовательность на private static let

2023-07-14 10:05 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2TokenStorage.swift
>  struct OAuth2TokenStorage {
Рекомендую реализовать синглтон, а bearerToken сделать не static

2023-07-14 10:05 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/ProfileService/ProfileImageService.swift
> +            self.task = nil
Рекомендую указать до switch

2023-07-14 10:05 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/ProfileService/ProfileService.swift
> +            self.task = nil
Тоже рекомендую указать до switch

2023-07-14 10:05 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                print(error.localizedDescription)
Лишние print рекомендую поубирать

2023-07-14 13:15 UTC, vadamask commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2Service.swift
> +            self.task = nil
Тут же смысл в том, что после результата надо обнулить задачу.

2023-07-14 13:23 UTC, vadamask commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                print(error.localizedDescription)
Я передал error в showAlert. Так делают?

2023-07-14 13:25 UTC, protos17 commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2Service.swift
> +            self.task = nil
Ну в этом блоке task уже отрабатывает, поэтому ее можно сразу обнулить, а результат ее работы мы completion передаем

2023-07-14 13:25 UTC, protos17 commented on ImageFeed/SplashViewController/SplashViewController.swift
> +                print(error.localizedDescription)
Да, конечно

2023-07-14 13:31 UTC, vadamask commented on ImageFeed/ServiceAccessLayer/OAuth2/OAuth2Service.swift
> +            self.task = nil
А гонки в таком случае не будет? Пункт 2 в чеклисте

2023-07-16 20:17 UTC, merged