Sprint 13
vadamask/ImageFeed pull request #6
Opened 2023-08-13 17:42 UTC by vadamask

Привет, подскажи плиз с градиентом. В случае ячеек, где должен располагаться метод добавления слоя с анимацией? Что-то в ините не срабатывает :)

2023-08-15 15:47 UTC, protos17 requested changes

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/TabBarController/ImagesList/ImagesListViewController.swift
> -        }
Для того, чтобы тест проходил, необходимо добавить проверку, что мы обращаемся к видимым ячейкам:

        if let visibleIndexPaths = tableView.indexPathsForVisibleRows,
           visibleIndexPaths.contains(indexPath) {
           ...

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/API/Services/ImagesListService.swift
> +                print(error.localizedDescription)
Здесь рекомендую показывать ошибку пользователю, иначе будет неясно, почему не отображаются ячейки. Для этого можно использовать completion, в который передавать ошибку

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/API/Services/ImagesListService.swift
> +                                isLiked: !oldPhoto.isLiked
Можно isLiked сделать переменной и менять только ее:

                   var photo = self.photos[index]
                   photo.isLiked.toggle()
                   self.photos[index] = photo

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/API/Services/ImagesListService.swift
> +                            assertionFailure("Photo not found")
Здесь тоже нужно передавать ошибку:

completion(.failure...

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/API/Services/ImagesListService.swift
> +                assertionFailure("Unknown error")
И здесь тоже:

completion(.failure

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/Auth/AuthHelper.swift
> +class AuthHelper: AuthHelperProtocol {
Класс без наследования рекомендую указать как final

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/Auth/AuthHelper.swift
> +    let configuration: AuthConfiguration
Рекомендую указать как private

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/Auth/WebViewPresenter.swift
> +    var authHelper: AuthHelperProtocol
Рекомендую указать как private let

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/Auth/WebViewPresenter.swift
> +            assertionFailure("Failed with making request")
Репкомендую показывать алерты с ошибками в таких случаях

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    let webView: WKWebView! = {
Для чего он сделан опциональным и принудительно извлекается? Он нормально работает и без опциональности.
Рекомендую убрать его из протокола и сделать приватным

2023-08-15 15:47 UTC, protos17 commented on ImageFeed/Core/Animations/GradientView.swift
> +    var gradientLayer: CAGradientLayer!
Рекомендую укзаать как private

2023-08-15 15:47 UTC, protos17 commented on ImageFeedTests/ImagesListTests.swift
> +class ImagesListTests: XCTestCase {
Тестовые классы также рекомендую указывать как final

2023-08-15 15:47 UTC, protos17 commented on ImageFeedUITests/ImageFeedUITests.swift
> +        XCTAssertTrue(app.staticTexts["bio"].exists)
Рекомендую удалить этот ассерт, потому что при отсутствии bio тест не проходит

2023-08-15 16:29 UTC, vadamask commented on ImageFeed/TabBarController/ImagesList/ImagesListViewController.swift
> -        }
Не понял, это к тесту должно относиться или к коду?

2023-08-15 16:31 UTC, protos17 commented on ImageFeed/TabBarController/ImagesList/ImagesListViewController.swift
> -        }
Да, для корректной простановки лайков

2023-08-15 16:50 UTC, vadamask commented on ImageFeed/Auth/WebViewViewController.swift
> +    let webView: WKWebView! = {
<img width="609" alt="Снимок экрана 2023-08-15 в 19 48 46" src="https://github.com/vadamask/ImageFeed/assets/53489821/77222602-bd7b-4dd8-ae6f-90c7e6d3d490">

Я для тестов это делал, чтобы занилить и не тратить ресурсы. Какой есть вариант в этом случае, просто проинициализировать в тесте?

2023-08-15 16:51 UTC, protos17 commented on ImageFeed/Auth/WebViewViewController.swift
> +    let webView: WKWebView! = {
Просто заинитить внутри теста

2023-08-15 16:56 UTC, vadamask commented on ImageFeed/Auth/WebViewViewController.swift
> +    let webView: WKWebView! = {
<img width="926" alt="Снимок экрана 2023-08-15 в 19 54 29" src="https://github.com/vadamask/ImageFeed/assets/53489821/c281df1e-e4cc-492b-9df8-fecbb7839b2f">

C приватностью другая проблема, я не смогу тогда презенетером подписаться на изменения у web view. А передать keypath  я не допер как :(

2023-08-15 17:20 UTC, vadamask commented on ImageFeed/Auth/WebViewViewController.swift
> +    let webView: WKWebView! = {
Короче просто передал целиком webView

2023-08-16 11:09 UTC, vadamask commented on ImageFeed/TabBarController/ImagesList/ImagesListViewController.swift
> -        }
Мы с наставником поняли, что это какая-то магия 🧐 можно объяснить как оно работает?

2023-08-17 11:06 UTC, protos17 commented on ImageFeed/TabBarController/ImagesList/ImagesListViewController.swift
> -        }
При свайпе вниз ячейки становятся невидимыми, т.е. уходят за пределы экрана. Чтобы можно было на них нажать, эта механика позволяет изменить нумерацию ячеек

2023-08-17 11:20 UTC, protos17 approved these changes

2023-08-17 11:20 UTC, protos17 commented on ImageFeed/API/Services/ImagesListService.swift
> +            print("Failed to make HTTP request")
Рекомендую доработать и показать ошибки пользователю

2023-08-17 11:20 UTC, protos17 commented on ImageFeed/Auth/WebViewPresenter.swift
> +    private var authHelper: AuthHelperProtocol
Рекомендую указать как let

2023-08-17 11:20 UTC, protos17 commented on ImageFeed/TabBarController/ImagesList/ImagesListPresenter.swift
> +                print(error.localizedDescription)
Рекомендую показать ошибку

2023-08-20 19:03 UTC, merged